Make pyjsonviewer callable from python code. #33
AtsushiSakai/PyJSONViewer pull request #38
Opened 2021-05-04 14:51 UTC by Ankush-Chander

- [ ] update `insert_node` function.
- [ ] update children nodes  in test cases

2021-05-04 14:53 UTC, Ankush-Chander commented
@AtsushiSakai Please review.

2021-05-06 12:08 UTC, AtsushiSakai requested changes

2021-05-06 12:08 UTC, AtsushiSakai commented on pyjsonviewer/pyjsonviewer.py
> +
Could you remove this empty line? PEP8 offers just one empty line should be between two functions.

2021-05-06 12:17 UTC, AtsushiSakai approved these changes
LGTM. Thanks.

2021-05-06 12:17 UTC, merged